-- AlterTable
ALTER TABLE "Circle" ALTER COLUMN "name" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "CircleSession" ALTER COLUMN "title" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "note" SET DATA TYPE VARCHAR(500);
